sudo: required
services:
  - docker

before_install:
  - docker build -t kingfabric2/dock-multi-frontend -f Dockerfile.dev .

script:
  - docker run kingfabric2/dock-multi-frontend npm run test -- --coverage